apiVersion: v2
name: cloudflare-operator
description: Helm chart for Cloudflare Operator
type: application
version: 0.0.21
appVersion: "0.0.15"
keywords:
  - cloudflare
  - operator
  - dns
  - dyndns
home: https://containeroo.github.io/cloudflare-operator
sources:
  - https://github.com/containeroo/cloudflare-operator
  - https://github.com/containeroo/helm-charts
maintainers:
  - name: rxbn
    email: rxbn@containeroo.ch
  - name: gi8
    email: gi8@containeroo.ch
annotations:
  "artifacthub.io/operator": "true"
  "artifacthub.io/links": |
    - name: Chart Source
      url: https://github.com/containeroo/helm-charts
    - name: Upstream Project
      url: https://github.com/containeroo/cloudflare-operator
